### ISSUE TITLE
Dúvida - Segunda via de um boleto gerado pelo banco

### ISSUE THREAD

**Issue by globsecure** [CobreGratis/boletophp#73]
Boa tarde Pessoal,

Talvez não seja o melhor lugar para uma dúvida sobre esse assunto. Mais estou precisando aumentar meu conhecimento referente a 2ª via de um boleto que o banco enviou e registro.

Por exemplo hoje, sou obrigado a entrar no sistema do Banco e emitir essa  segunda via, pois muitos clientes relatam não recebe a primeira via. 

Qual é a ideia usar essa belíssima biblioteca criado pela comunidade, porém no meu caso apenas para segunda via.

O que isso implica?

1) O banco que gera e ele é detentor do nosso número e registro
2) Com o arquivo de retorno ou remessa do Banco, que me informa os titulos gerados e enviados. Eu tenho informações elas são suficiente para uma segunda via gerada por mim?

Agradeço muito a contribuição de todos!

Att

**Comment by diego-vieira** [comment]
@globsecure não sei se resolveu, mas neste caso foge um pouco do conceito do boletophp, então você precisará ter todos os dados do boleto que foi gerado pelo banco e replicar os números, especialmente o código de barras/IPTE.

**Comment by globsecure** [comment]
@diego-vieira - Acabei de cair nesse assunto de novo e lembrei que eu tinha aberto essa pergunta. Ainda não conseguir uma solução, até porque a mesma foi deixado de lado, agora retornou com força total e realmente acho que a única solução é ter as informações, e remontar o boleto.

No caso da segunda via que não é um boleto registrado não ficaria mais fácil?

**Comment by diego-vieira** [comment]
No caso de registrado, não tem como. A menos que vc tenha os dados registrado no banco e assim remontar o boleto com os dados do registro do banco. Se não for registrado é como emitir um boleto normal.

**Comment by EdersonTS** [comment]
@globsecure tua intenção é remontar o mesmo boleto que foi "enviado" da primeira vez? exatamente igual? ou pretende mudar alguma coisa como data ou valor?

acredito que, se você tem todos os dados do boleto 1ª via, é só "clonar" o boleto
eu acho que não terás problema com isso.
(muitos atendentes de banco não sabem dar muitas explicações pois são treinados pra seguir o protocolo, então se pedir isso pra algum será guiado a utilizar o sistema do banco pra gerar outra via)

**Comment by globsecure** [comment]
@EdersonTS na verdade o objetivo seria dar ao cliente a opção de segunda via de um boleto enviado pelo banco. Esse boleto é gerado e enviado pelo banco, então muitas vezes o cliente gostaria da segunda via... Gostaria de fornecer para ele uma opção diretamente no meu sistema. 

Então em resumo talvez mudaria apenas data e melhor ainda se coloca-se juros em caso de atraso. Porém por ser registrado acredito não poder.

**Comment by EdersonTS** [comment]
@globsecure infelizmente não sei te dizer, se eu fosse o banco, registraria o boleto utilizando o código digitável, isso impediria que o cliente gere um novo boleto com informação diferente (data ou juros). mas, como disse, não sei se eles fazem isso então não sei confirmar, acredito que se tu precisar emitir uma segunda via exatamente igual não terá problema, mas não pode mudar o valor nem a data, pois eles influenciam na linha digitável.

não sei se fui claro, mas espero ter ajudado
