### ISSUE TITLE
Fator de vencimento - ITAU

### ISSUE THREAD

**Issue by mmfjunior1** [CobreGratis/boletophp#92]
[RESOLVIDO - Qualquer uma das formas acaba resultando no mesmo valor]
Boa tarde.
Estou acompanhando a documentação do CNAB 400 do ITAU e o cálculo do fator de vencimento disposto no na documentação deles difere do que está no projeto.
Gostaria de saber qual devo utilizar, nesse caso, pois a representação numérica do código de barras acaba ficando diferente da que esta'sendo gerada pelo boletoPHP.

O cálculo está na página 60 do arquivo anexo. Já tenho uma modificação aqui, se quiser, posso subir.
Fico no aguardo.
Abraços.
[layout_cobranca_400bytes_cnab_itau-1.pdf](https://github.com/CobreGratis/boletophp/files/619743/layout_cobranca_400bytes_cnab_itau-1.pdf)

**Comment by edvanmc** [comment]
Esse cálculo foi implementado na issue #63 mas apenas para um banco.

Veja link abaixo:

https://github.com/CobreGratis/boletophp/pull/63

Att.,

Edvan

Em 29/11/2016 15:50, "mmfjunior1" <notifications@github.com> escreveu:
